name: Bun Release

on:
  push:
    branches:
      - develop

permissions:
  id-token: write

jobs:
  release:
    uses: jondotsoy/jondotsoy/.github/workflows/bun-release-package.yml@main
    permissions:
      id-token: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
